//
// ApiResponseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiResponseDto: Codable, JSONEncodable, Hashable {

    public var data: AnyCodable?
    public var error: String?

    public init(data: AnyCodable?, error: String?) {
        self.data = data
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(error, forKey: .error)
    }
}

