//
// GetAllReceiptsDefaultResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAllReceiptsDefaultResponse: Codable, JSONEncodable, Hashable {

    public var data: [ReceiptDTO]?
    public var total: Int?
    public var page: Int?
    public var limit: Int?

    public init(data: [ReceiptDTO]? = nil, total: Int? = nil, page: Int? = nil, limit: Int? = nil) {
        self.data = data
        self.total = total
        self.page = page
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case total
        case page
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(limit, forKey: .limit)
    }
}

