//
// TransactionDetailsDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionDetailsDTO: Codable, JSONEncodable, Hashable {

    public var purchasedAt: Date
    public var fiscalReceiptNumber: String
    public var manufacturingNumber: String

    public init(purchasedAt: Date, fiscalReceiptNumber: String, manufacturingNumber: String) {
        self.purchasedAt = purchasedAt
        self.fiscalReceiptNumber = fiscalReceiptNumber
        self.manufacturingNumber = manufacturingNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case purchasedAt
        case fiscalReceiptNumber
        case manufacturingNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(purchasedAt, forKey: .purchasedAt)
        try container.encode(fiscalReceiptNumber, forKey: .fiscalReceiptNumber)
        try container.encode(manufacturingNumber, forKey: .manufacturingNumber)
    }
}

